import { AuthPopupProvider } from '@/app/context/AuthPopupContext';
import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const poppins = Poppins({
	subsets: ['latin'],
	variable: '--font-poppins--poppins-font',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable} antialiased`}>
				<Toaster />
				{/* <LoaderWrapper>{children}</LoaderWrapper> */}
				<AuthPopupProvider>{children}</AuthPopupProvider>
			</body>
		</html>
	);
}
