import Header from '@/app/components/header/Header';
import { Provider } from '@/app/providers/Provider';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const poppins = Poppins({
	subsets: ['latin'],
	variable: '--font-poppins--poppins-font',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable} antialiased`}>
				<Provider>
					<Header />
					<div className="my-5 container">{children}</div>
				</Provider>
				{/* <Toaster /> */}
				{/* <LoaderWrapper>{children}</LoaderWrapper> */}
				{/* <AuthPopupProvider>{children}</AuthPopupProvider> */}
			</body>
		</html>
	);
}
